apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  admin.enabled: 'true'
  users.anonymous.enabled: 'false'

  configManagementPlugins: |
    - name: kustomize2
      generate:
        command: ["bash", "-c", "kustomize build ."]
        args: []