apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.4.0
- git-askpass.yaml
- github-credentials.yaml

patchesJson6902:
- target:
    kind: Deployment
    name: argocd-repo-server
  path: patch-file.yaml

patchesStrategicMerge:
  - argocd-cm.yaml
